sudo: false
cache: bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.4
  - 2.3.0
gemfile:
  - Gemfile
  - gemfiles/Gemfile-rails.5.2.x
  - gemfiles/Gemfile-rails.5.1.x
  - gemfiles/Gemfile-rails.5.0.x
  - gemfiles/Gemfile-rails.4.2.x
matrix:
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile-rails.5.2.x
  - rvm: 2.0.0
    gemfile: gemfiles/Gemfile-rails.5.2.x
  - rvm: 2.1.5
    gemfile: gemfiles/Gemfile-rails.5.2.x
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile-rails.5.1.x
  - rvm: 2.0.0
    gemfile: gemfiles/Gemfile-rails.5.1.x
  - rvm: 2.1.5
    gemfile: gemfiles/Gemfile-rails.5.1.x
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile-rails.5.0.x
  - rvm: 2.0.0
    gemfile: gemfiles/Gemfile-rails.5.0.x
  - rvm: 2.1.5
    gemfile: gemfiles/Gemfile-rails.5.0.x
  - rvm: 1.9.3
    gemfile: Gemfile
  - rvm: 2.0.0
    gemfile: Gemfile
  - rvm: 2.1.5
    gemfile: Gemfile
notifications:
  email: false
  slack:
    on_pull_requests: false
    on_success: change
    on_failure: always
    secure: Qr9/3LRW22qAoJ/9mynVKiI1p/AVIdW4GqcaymMjC6KH46EUwtbB4DxBa3K+gfBYOcfDKDe0vt3TUL/FMCgchqHum5QaNrAfSLj6k363sZqqW+dEuEMJO2e+QsIQUexBnDDQIJNSnr5DqoQ5+npZ8YwzWeAp8nRUs5uYI/RlXXo=
