cache: bundler
language: ruby
rvm:
  - '2.4'
  - '2.5'
  - '2.6'
  - '2.7'
gemfile:
  - Gemfile
  - gemfiles/Gemfile-rails.head
  - gemfiles/Gemfile-rails.6.0.x
  - gemfiles/Gemfile-rails.5.2.x
  - gemfiles/Gemfile-rails.5.1.x
  - gemfiles/Gemfile-rails.5.0.x
matrix:
  exclude:
  - rvm: '2.4'
    gemfile: Gemfile
  - rvm: '2.4'
    gemfile: gemfiles/Gemfile-rails.6.0.x
  - rvm: '2.4'
    gemfile: gemfiles/Gemfile-rails.head
  - rvm: '2.7'
    gemfile: gemfiles/Gemfile-rails.5.0.x
  - rvm: '2.7'
    gemfile: gemfiles/Gemfile-rails.5.1.x
  - rvm: '2.7'
    gemfile: gemfiles/Gemfile-rails.5.2.x
notifications:
  email: true
